#!/bin/sh

case "$1" in
        start)
                echo "Starting MQTT Subscribe."
		mosquitto_sub -h localhost -t test
        ;;
        stop)
	;;	
        *)
                echo "Usage: $0 {start|stop}"
        exit 1
esac
exit 0

